name: Trigger Netlify Build
on:
    workflow_dispatch:
jobs:
    build:
        name: Netlify Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Curl request
              run: curl -X POST -d {} https://api.netlify.com/build_hooks/66789164235f9beef6a5c220
